export const SET_CATALOG_REF = 'SET_CATALOG_REF'
export const SET_ABOUT_REF = 'SET_ABOUT_REF'
export const SET_MANUFACTURERS_REF = 'SET_MANUFACTURERS_REF'
export const SET_CONTACTS_REF = 'SET_CONTACTS_REF'

export const SET_SECTIONS_REFS = 'SET_SECTIONS_REFS'
export const CLEAR_SECTIONS_REFS = 'CLEAR_SECTIONS_REFS'
